disabled_rules: # rule identifiers to exclude from running
    - line_length
    - file_length
    - function_body_length
    - type_body_length
    - todo
    - cyclomatic_complexity
    - conditional_binding_cascade
    - vertical_whitespace
#   - colon
    - comma
#   - control_statement
# opt_in_rules: # some rules are only opt-in
#   - empty_count
#   - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
# included: # paths to include during linting. `--path` is ignored if present.
#   - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  # - Carthage
  - Pods
  - WebRTC

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly
# force_try:
#   severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 120
# they can set both implicitly with an array
# type_body_length:
#   - 300 # warning
#   - 400 # error
# or they can set both explicitly
file_length:
  warning: 800
  error: 1200
function_body_length:
  warning: 50
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
variable_name:
  # min_length: # only min_length
    # error: 4 # only error

  excluded: # excluded via string array
    - id
    - to
    - m
#     - URL
#     - GlobalAPIKey
# reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)